### ISSUE TITLE
Current RML_tidy csv has duplicates for Hypotaurine and O-acetylcarnitine

### ISSUE THREAD

**Issue by wkumler** [IngallsLabUW/Ingalls_Standards#20]
Not sure where the duplication is occurring, but we've got double entries for these two compounds in the current RML_Tidy branch. Differences are only showing up in the "Priority" column and the "Compound_Type" column so this may be on me. Happy to help debug but am just creating this to track it while I'm in the middle of other things

**Comment by R-Lionheart** [comment]
Ok I took a quick look and they're technically not duplicates; they have differences in the "Priority" column. I can't recall what we decided to do with that column, I think we were set to ditch it. I will check with Laura.

**Comment by wkumler** [comment]
I think there's also some differences in the compound_type column, but I can't tell if that's because there's a left_join somewhere in there that's creating a second set or if I just left those as NAs when I did my first pass through. The NA entries can be deleted entirely though!

**Comment by R-Lionheart** [comment]
As far as I can see the only differences are caused by the Priority column on both compounds. I did just pull the latest version before checking but I feel like I might be behind because my Compound_Type column still has "New2" for O-acetylcarnitine.

**Comment by R-Lionheart** [comment]
Will, I did a fresh pull and double checked those columns but to me it still looks like the only duplication issues are in the Priority column which I believe can be ditched anyway. I think between this and Issue #21 we should have a brief meeting with Laura when she's in tomorrow Tuesday the 2nd and we can resolve those problems and (finally) merge the RML_tidy branch. What do you think?
