### ISSUE TITLE
Sucrose 13C should be Sucrose 13C12

### ISSUE THREAD

**Issue by wkumler** [IngallsLabUW/Ingalls_Standards#21]
We've got sucrose at an m/z of 341.10839 which matches Pubchem's 342.11621 minus a hydrogen (341.1089) but our sucrose 13C IS m/z is 353.1497 which can't be correct if it's only got one 13C label. Based on the chemical formula it looks like all 12 carbons are labeled, which tracks with the masses and should be included in the name.

We should review all the IS names and make sure that they're properly described — I'm also seeing Thiamine, 13C3 mislabeled with the number of carbons (should be 4?)

@LTCarlson do I understand what's happening here correctly?

**Comment by R-Lionheart** [comment]
For the m/z column, those are the values from the original sheet and haven't been filled in from an automatic script (like the formulas/names etc columns). If anything needs to be edited that will probably need to be reviewed by hand.

**Comment by wkumler** [comment]
Yeah, this error has been around since Katherine's original worksheet and I agree it'll need to be reviewed by hand. I think it's just the names that are incorrect, the mass seems to match the original formula. But I'm not certain of that.

**Comment by LTCarlson** [comment]
I am happy to double check the names and masses of all the internal standards.  I also have the peak quality table ready to put up.  While I was going through that, I did notice a few duplicates that I think can be deleted.
