### ISSUE TITLE
Request: keep internal standards same name as unlabeled

### ISSUE THREAD

**Issue by wkumler** [IngallsLabUW/Ingalls_Standards#32]
I was recently surprised that we have an internal standard for Sulfolactate (3-Sulfolactate, 13C3) without the unlabeled version. When I did some deeper digging, I realized that the unlabeled version had been renamed to Sulfolactic acid. It'd be great if we could make a lab rule to keep the internal standards as the same name as the unlabeled version to allow us to better compare the two. In the meantime, it'd be great to learn how many other IS have different names from their unlabeled versions.

**Comment by R-Lionheart** [comment]
I can add that to the README as one of our conventions moving forwards. As for troubleshooting the existing names, maybe that could be a good project for someone new coming into the lab; get familiar with our compounds, learn R if they are new to it?

**Comment by R-Lionheart** [comment]
I have replaced the unlabeled Sulfolactic acid with Sulfolactate
