### ISSUE TITLE
beta-Alanine betaine and Leucine/Isoleucine should have same exact mass

### ISSUE THREAD

**Issue by wkumler** [IngallsLabUW/Ingalls_Standards#33]
They've got the same molecular formula, so their exact masses should be identical. Instead, bAb is in there at 132.1018 and L/I are in there at 132.102454 for a ppm difference of nearly 5. And the calculated mass from PubChem (131.094628 + 1.007276) is somewhere in the middle, at 132.101905.

**Comment by R-Lionheart** [comment]
Is the exact mass something we can just manually fix and push? And are you only seeing the calculated mass issue for this compound?

**Comment by wkumler** [comment]
This is probably fine to fix one-off! But there may be other so it might be best to write a unit test or something that scans through and calculates the exact mass the same way each time. I know at one point we were using the exact mass we got from the instrument though so maybe one of these is empirical and one is theoretical? @LTCarlson do you remember where these masses came from?

**Comment by R-Lionheart** [comment]
I can manually replace this one with the calculated mass from Pubchem and keep this issue open as a future todo item, is that calculated mass the one(s) we want to use?

**Comment by LTCarlson** [comment]
There is an exact mass calculator that I like to use and then I always check it against the mass we see on the instrument.  So I would like to keep doing that.  I must have made a mistake on beta-Alanine betaine.

**Comment by wkumler** [comment]
Oh neat - so the values in the spreadsheet are the exact masses that come out of the calculator? I remember chatting about this with Katherine and for some reason I thought they were empirical at one point, but I do think the calculator is the way to go long-term.

**Comment by R-Lionheart** [comment]
And checking that the getExactMass.R script is the calculator you are using? Or do you have a different one?
