### ISSUE TITLE
riboflavin-5-phosphate mz incorrect for RP

### ISSUE THREAD

**Issue by kheal** [IngallsLabUW/Ingalls_Standards#43]
riboflavin-5-phosphate's RP record is incorrect for the z = 1 record.  

the ion form is listed as [M-H]-, but the z is +1.  Either we need to change the ion form to [M+H]+ and the m/z accordingly or remove this line (changing z to -1 creates a repeat).

**Comment by LTCarlson** [comment]
Wow, good catch.  I fixed it and uploaded a new file, hopefully that works.

**Comment by kheal** [comment]
Looks good, thanks!  I'll close this.
